CREATE TABLE BOOK
(
    ID IDENTITY(6,6) NOT NULL,
    TITLE       VARCHAR2(150) NOT NULL,
    AUTHOR      VARCHAR2(150) NOT NULL,
    DESCRIPTION VARCHAR2(150),
    CONSTRAINT BOOK_PK PRIMARY KEY (ID)
);

INSERT INTO BOOK (ID, TITLE, AUTHOR, DESCRIPTION)
VALUES (1, 'Crime and Punishment', 'F. Dostoevsky', NULL);
INSERT INTO BOOK (ID, TITLE, AUTHOR, DESCRIPTION)
VALUES (2, 'Anna Karenina', 'L. Tolstoy', NULL);
INSERT INTO BOOK (ID, TITLE, AUTHOR, DESCRIPTION)
VALUES (3, 'The Brothers Karamazov', 'F. Dostoevsky', NULL);
INSERT INTO BOOK (ID, TITLE, AUTHOR, DESCRIPTION)
VALUES (4, 'War and Peace', 'L. Tolstoy', NULL);
INSERT INTO BOOK (ID, TITLE, AUTHOR, DESCRIPTION)
VALUES (5, 'Dead Souls', 'N. Gogol', NULL);
COMMIT;